---
  bind:
    host: '0.0.0.0' # listen host middleware
    ports: [80, 443] # listen port middleware
  destination:
    host: '127.0.0.1' # local host of ssh and stunnel
    ports:
      tcp: 22 # ssh port
      tls: 4433 # stunnel port
...
